name: Deploy

on:
  push:
    tags:
      - v2.*
      - '!v2.0.0-alpha*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: cp -r docs/.vitepress/dist .temp
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false
      - run: rm -rf v2
      - run: mkdir -p v2
      - run: cp -rf .temp/* v2
      - run: rm -r .temp
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
      - run: git add v2
      - run: git commit --message "${{ github.ref_name }}"
      - run: git push
